use_frameworks!

target 'FlatActionSheetController_Example' do
  pod 'FlatActionSheetController', :path => '../'

  target 'FlatActionSheetController_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
  end
end
